[build]
target = "targets/x86_64-unknown-uefi-kernel.json"

[unstable]
build-std = ["core", "alloc"]

[target.x86_64-unknown-uefi-kernel]
runner = ["sh", "-c", "mkdir -p dev/esp/EFI/BOOT && cp \"$1\" dev/esp/EFI/BOOT/BOOTX64.EFI && qemu-system-x86_64 -cpu qemu64,level=13,+fsgsbase,+xsave,+xsaveopt,+xsaveerptr -m 512 -no-shutdown -no-reboot -nographic -serial mon:stdio -drive if=pflash,format=raw,unit=0,readonly=on,file=/usr/share/edk2/x64/OVMF_CODE.4m.fd -drive if=pflash,format=raw,unit=1,file=./dev/OVMF_VARS.fd -drive format=raw,file=fat:rw:./dev/esp,media=disk", "placeholder"]
rustflags = ["-C", "link-args=/debug:dwarf"]


