[build]
target = "targets/x86_64-unknown-uefi-kernel.json"

[unstable]
build-std = ["core", "alloc"]

[target.x86_64-unknown-uefi-kernel]
runner = ["sh", "-c", "[ -f \"./ovmf/OVMF_CODE.4m.fd\" ] && [ -f \"./ovmf/OVMF_VARS.fd\" ] && echo \"\n\x1b[32mINFO\x1b[37m: running qemu\" && mkdir -p target/esp/EFI/BOOT && cp \"$1\" target/esp/EFI/BOOT/BOOTX64.EFI && qemu-system-x86_64 -cpu qemu64,level=13,+fsgsbase,+xsave,+xsaveopt,+xsaveerptr -m 512 -no-shutdown -no-reboot -nographic -serial mon:stdio -drive if=pflash,format=raw,unit=0,readonly=on,file=./ovmf/OVMF_CODE.4m.fd -drive if=pflash,format=raw,unit=1,file=./ovmf/OVMF_VARS.fd -drive format=raw,file=fat:rw:./target/esp,media=disk || echo \"\n\x1b[31mERROR\x1b[37m: ./ovmf/OVMF_CODE.4m.fd and ./ovmf/OVMF_VARS.fd must be present in order to run QEMU with UEFI\"", "placeholder"]
rustflags = ["-C", "link-args=/debug:dwarf"]


